#!/usr/bin/env bash
#
# Build the three application images and package them for a machine that will
# never see this source tree. Run it HERE, from the repo root.
#
#   ./deploy/release.sh 1.0.0 --push ghcr.io/youruser
#   ./deploy/release.sh 1.0.0 --save
#
# --push  tags for a registry and pushes. The client machine pulls. Updates
#         later are incremental, because Docker reuses the layers it already
#         has — this is the option to want.
# --save  writes .tar files instead. No registry, no account, no credential on
#         the client machine, and no internet needed there — but every update
#         is a full multi-gigabyte transfer again.
#
# Either way it writes deploy/dist/, which is the whole handover: a compose
# file, an .env to fill in, and (with --save) the images.
#
# WHAT THIS DOES NOT DO IS HIDE THE CODE. The worker image ships
# workers/src/*.py as plain Python, and the API image ships readable compiled
# JavaScript. Anyone with the image can `docker cp` them out. This is
# packaging, not licensing.
set -euo pipefail

cd "$(dirname "$0")/.."

TAG="${1:-}"
MODE="${2:-}"
REGISTRY="${3:-}"

if [[ -z "$TAG" || ( "$MODE" != "--push" && "$MODE" != "--save" ) ]]; then
  cat >&2 <<USAGE
usage: $0 <version> --push <registry-prefix>
       $0 <version> --save

  $0 1.0.0 --push ghcr.io/youruser
  $0 1.0.0 --save
USAGE
  exit 1
fi
if [[ "$MODE" == "--push" && -z "$REGISTRY" ]]; then
  echo "--push needs a registry prefix, e.g. ghcr.io/youruser" >&2
  exit 1
fi

# The client machine's architecture, not this one's. An image built on an ARM
# Mac will not run on an Intel laptop and the error names an exec format, not
# a platform. Override for an ARM client: CDIP_PLATFORM=linux/arm64.
PLATFORM="${CDIP_PLATFORM:-linux/amd64}"

OUT="deploy/dist"
IMAGES=(api web worker)

step() { printf '\n\033[1;34m==>\033[0m %s\n' "$1"; }

step "Building for $PLATFORM at version $TAG"
docker build --platform "$PLATFORM" -f apps/api/Dockerfile   -t "cdip-api:$TAG"    .
docker build --platform "$PLATFORM" -f deploy/Dockerfile.web -t "cdip-web:$TAG"    . \
  --build-arg VITE_API_URL=/api
docker build --platform "$PLATFORM" -t "cdip-worker:$TAG" ./workers

rm -rf "$OUT"
mkdir -p "$OUT"

if [[ "$MODE" == "--push" ]]; then
  REGISTRY="${REGISTRY%/}"          # normalize: the compose file adds the slash
  # `docker login` takes the HOST, not the full path — `docker login
  # ghcr.io/you` is an error, and a confusing one.
  REGISTRY_HOST="${REGISTRY%%/*}"
  step "Pushing to $REGISTRY"
  for i in "${IMAGES[@]}"; do
    docker tag "cdip-$i:$TAG" "$REGISTRY/cdip-$i:$TAG"
    docker push "$REGISTRY/cdip-$i:$TAG"
  done
  PREFIX="$REGISTRY/"
else
  step "Saving images to $OUT (this takes a few minutes and a few GB)"
  # One tar per image rather than one combined: a transfer that dies partway
  # can be resumed a file at a time, and AnyDesk's file transfer is exactly
  # where that matters.
  for i in "${IMAGES[@]}"; do
    docker save "cdip-$i:$TAG" | gzip > "$OUT/cdip-$i-$TAG.tar.gz"
  done
  PREFIX=""
fi

step "Writing the handover bundle"
cp deploy/docker-compose.dist.yml "$OUT/docker-compose.yml"

# The client's .env is GENERATED from the same template this repo documents, so
# the two cannot drift into describing different variables.
{
  echo "# Generated by deploy/release.sh for version $TAG."
  echo "# Fill in the marked values on the client machine, then:"
  echo "#   docker compose up -d"
  echo
  echo "CDIP_IMAGE_PREFIX=$PREFIX"
  echo "CDIP_TAG=$TAG"
  echo
  # Skipping the template's own header, which is addressed to whoever is
  # setting up the server PC from a checkout — not to this bundle's reader.
  awk 'f || /^# --- the storage switch/ { f = 1; print }' deploy/.env.local.example \
    | grep -v '^STORAGE_DATA_DIR='
} > "$OUT/.env.template"

cat > "$OUT/README.txt" <<TXT
CDIP $TAG — install bundle

On the client machine:
  1. Install Docker Desktop (Windows: it will install WSL2 itself).
  2. Copy this whole folder somewhere, e.g. C:\\cdip.
  3. Rename .env.template to .env and fill in the values it marks EDIT THIS.
     At minimum: LOCAL_S3_PUBLIC_ENDPOINT, APP_URL, POSTGRES_PASSWORD,
     LOCAL_S3_SECRET, and the model API keys.
$(if [[ "$MODE" == "--save" ]]; then
    echo "  4. Load the images:  for f in *.tar.gz; do docker load -i \$f; done"
    echo "     (PowerShell:      Get-ChildItem *.tar.gz | % { docker load -i \$_ })"
    echo "  5. docker compose up -d"
  else
    echo "  4. docker login $REGISTRY_HOST   (with the pull-only token you were given)"
    echo "  5. docker compose up -d     (this pulls the images the first time)"
  fi)

Then open the address you put in APP_URL.

Full instructions: docs/client-install.md in the source repository.
TXT

step "Done — $OUT"
ls -lh "$OUT"
